# Generated by Django 5.1.11 on 2025-10-20 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'permissions': [('basic', 'Basic Perm'), ('pro', 'Pro Prem'), ('advanced', 'Advanced Perm')]},
        ),
    ]
