# Generated by Django 5.1.11 on 2025-10-20 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscriptions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptions',
            options={'permissions': [('basic', 'Basic Perm'), ('pro', 'Pro Prem'), ('advanced', 'Advanced Perm'), ('basic_ai', 'Basic AI Perm')]},
        ),
    ]
