# Generated by Django 5.1.11 on 2025-10-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subscriptions', '0004_subscriptions_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='permissions',
            field=models.ManyToManyField(to='auth.permission'),
        ),
    ]
